### ISSUE TITLE
edat.txt file, and data.csv files are not there.

### ISSUE THREAD

**Issue by nishu1193** [singularity014/Keyword-Extraction-Bidirectional-LSTM#2]
I am not sure for what e_dat.txt is getting used and how it looks like . please can u brief? Also why its not present in repo. Also there is a file named data.csv in codebase which is also not present.  also for what purpose we are using wiki-collector-data. i

**Comment by singularity014** [comment]
Hello,

**Comment by singularity014** [comment]
Hi, 
For e_dat.txt u can use embedding file. You may use glove or word2vec embedding files, its available on internet.
wiki-collector-data -  is used to collect data from wikipedia, it scrapes sentences and performs 

Data.csv was an uncleaned data which was collected by running the wiki-collector script. Wiki collector collects the data from wikipredia and performs labelling with rake, but then later rake keywords were dropped and SGRank keywords were used(i added the comment in data-cleaner code).

This was not included, as main purpose of the repo was to experiment on model level, but you may run the code, and see it will start generating it . data-cleaner further cleans the wikpedia collected data and labels again using sgrank method.

**Comment by singularity014** [comment]
@nishu1193 
Hi,
For e_dat.txt u can use embedding file. You may use glove or word2vec embedding files, its available on internet.
wiki-collector-data - is used to collect data from wikipedia, it scrapes sentences and performs

Data.csv was an uncleaned data which was collected by running the wiki-collector script. Wiki collector collects the data from wikipredia and performs labelling with rake, but then later rake keywords were dropped and SGRank keywords were used(i added the comment in data-cleaner code).

This was not included, as main purpose of the repo was to experiment on model level, but you may run the code, and see it will start generating it . data-cleaner further cleans the wikpedia collected data and labels again using sgrank method.

**Comment by nishu1193** [comment]
Hi I am still not sure about Data.csv file . I got it that you scraped wikipedia data into a file named "wiki-collector-data". Is data.csv file made from this "wiki-collector-data". If yes then what processing i have to do for that?

**Comment by singularity014** [comment]
They are same, file, thanks for pointing out. I will rename it.

**Comment by nishu1193** [comment]
Thasnk you for your guidance i hope u will not mind if i ask some questions regarding it in future . Actually i am having a used case which i think i can solve with this repo help

**Comment by singularity014** [comment]
You're welcome. 
This repo was more of a personal precursor experiment catering to a bigger project, mentioned in this paper.
However, the code for this paper is a proprietary.
[https://www.preprints.org/manuscript/201908.0073/v1](url)
I'll be adding more projects using Transformer  and BERT model applications. more Organised :) stay tuned.

**Comment by nishu1193** [comment]
Hi 

Actually i was wondering that a file named "data_l.csv" is getting created in "data-cleaner-labeller.py". I think its the same file as "wikidata.csv". Can you please give a little clarity on this.
